#!/usr/bin/python3

'''
Author: KrakenBinary
DevTools: Geany, pycodestyle, pyflakes3, pylint
Des: This will become a tool for CTF file analysis
'''

import sys


class Analysis:
    '''lets hold data in the class I suppose?'''
    dir_file = None  # This is the directory + file location
    flag_temp = None  # This is the string "format" (ex: 'flag{}')

    @classmethod
    def get_loc(cls):
        '''get the file location for our target'''
        print('File path currently set to: ', cls.dir_file)

    @classmethod
    def set_loc(cls, dir_str):
        '''set the file location for our target'''
        cls.dir_file = dir_str
        print('directory path now set to: ', cls.dir_file)


def quit_me():
    '''exit the application'''
    sys.exit()


def parse_me(string_in):
    '''parse input for various things'''
    command, value = (string_in.split(" ") + [None])[:2]
    if not value:
        if command in blank_commands:
            blank_commands[command]()
    elif command in commands:
        commands[command](value)
    else:
        print('Something went sideways, returing to main')
        main()


def help_me():
    '''this is the basic application help information.'''
    print('\nWelcome to Simulacrum. Please use the following commands:')
    print('---------------------------------------------------------')
    print('    - h  | help information')
    print('    - q  | quit this application')
    print('    - gd | get directory that is currently set')
    print('    - sd | set direcotry (includes filename)')
    print('\n---------------------------------------------------------')
    print('The following is an example usage:')
    print('$> sd ~/home/krakenbinary/Downloads/ocean.py')


def main():
    '''main loop'''
    help_me()
    while True:
        user_input = input('$> ')
        # print(user_input)
        parse_me(user_input)


commands = {
    'sd': Analysis.set_loc
    }


blank_commands = {
    'q': quit_me,
    'h': help_me,
    'gd': Analysis.get_loc
    }


main()
